apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mynode-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2


